### PR TITLE
Removed failing federated template

### PR DESCRIPTION
**Pull request by edwardalee**
This PR removes one of the template files which fails in testing.  Nobody uses these template files anyway. They really aren't very useful, so the mysterious error is not worth the trouble of tracking down.

### CODE REVIEW

**Comment by lhstrh** [comment]
https://github.com/lf-lang/epoch/blob/f901daa2277fe502545ba9942c5b7b5694394bec/org.lflang.ui/src/org/lflang/ui/wizard/LFProjectTemplateProvider.java#L99 needs to also be removed, or else someone could click on that option and get a runtime error.

**Review by lhstrh — APPROVED** [review]
LGTM!

**Comment by lhstrh** [comment]
Looks like there is a dangling reference to `FederatedProject` (compilation error).

**Comment by edwardalee** [comment]
> Looks like there is a dangling reference to `FederatedProject` (compilation error).

Just pushed a fix to that...  Interestingly, I got no error running the tests locally.

**Review by lhstrh — APPROVED** [review]

**Pull request merged**
