### PR TITLE
Uclid5-based LF Verifier

### LINKED ISSUE #19: Add the antlr maven plugin to epoch
So that the verifier feature https://github.com/lf-lang/lingua-franca/pull/1271 can be brought to epoch.

### PR DESCRIPTION
**Pull request by a-sr**
Fixes #19. Added dependencies and build configuration for https://github.com/lf-lang/lingua-franca/pull/1271

Similar to the Kotlin sources, the verifier code will not work if Epoch is started from within Eclipse but should work in the final product.

### CODE REVIEW

**Comment by a-sr** [comment]
@lsk567 I couldn't yet test if the verifier will actually work in Epoch because I don't have the necessary models at hand but I confirmed that the corresponding classes are in the product.
Could you please check if all works as intended?
You can use the artifact from the CI build https://github.com/lf-lang/epoch/actions/runs/5631324501

**Comment by lsk567** [comment]
I can confirm that epoch builds successfully on my end. Thanks so much for your help, @a-sr!

However, I have discovered two remaining issues, which I am looking into:

1. the `Compile LF Program` button is not yet working. Some classes are not being found at runtime even though they seem to be included.
Screen-Shot-2023-07-24-at-12 36 53-AM

2. There is another error that says ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.10.1. This is the case even when I changed the MANIFEST.MF to org.antlr.runtime;bundle-version="4.7.2".
```
Warning: Verification using "@property" and "--verify" is an experimental feature. Use with caution.
Information: Generating code for: platform:/resource/lf-verifier-benchmarks/benchmarks/src/ADASModel.lf
Information: Generation mode: EPOCH
Information: Generating sources into: /Users/shaokai/Documents/projects/lingua-franca/verification/lf-verifier-benchmarks/src-gen/benchmarks/src/ADASModel
The models will be located in: /Users/shaokai/Documents/projects/lingua-franca/verification/lf-verifier-benchmarks/mod-gen/benchmarks/src/ADASModel
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.10.1
```

**Comment by a-sr** [comment]
I pushed a commit that restricts the version of the antlr runtime to 4.7.2.
In my local test, the version warning did no longer occur and neither the class initialization error.
Could you confirm that?

**Comment by lsk567** [comment]
> I pushed a commit that restricts the version of the antlr runtime to 4.7.2.
> In my local test, the version warning did no longer occur and neither the class initialization error.
> Could you confirm that?

Yes! I can confirm that everything works beautifully. Thanks again for spending time looking into this PR, @a-sr !

Screen Shot 2023-07-24 at 10 55 24 PM

**Review by lsk567 — APPROVED** [review]

**Pull request merged**
